language: php
php:
  - 7.2.15

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - bin/sculpin generate --env=prod --port=8888
  - php -S 0.0.0.0:8888 -t ./output_prod/ &

script: bin/codecept run