version: '3.4'
volumes:
  site:
  vendor:

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
    - '80:80'
    - '443:443'
    links:
    - howtocodewell_fm
    restart: always
    volumes:
    - /data/ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: 'howtocodewellfm.com -> http://howtocodewell_fm'
      STAGE: 'local'
      FORCE_RENEW: 'false'

  howtocodewell_fm:
    build:
      context: .
      target: prod-env
    restart: always
    volumes:
        - .:/var/www/html
        - ./apache2/prod/config/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
        - ./apache2/prod/config/php/php.ini:/usr/local/etc/php/php.ini
        - site:/var/www/html/output_prod
        - vendor:/var/www/html/vendor
    environment:
        - APACHE_DOCUMENT_ROOT=/var/www/html/output_prod