google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: ayigDzQ0KKA
    podcast_id: 10499051
    guest: Ines van Essen
    guests_twitter: motherofcode
    profile_img: t-MDnclS_400x400.jpg

schedule:
  -
    "guest": "Oliver Davies"
    "date": "19-07-19"
    "twitter_handle": "opdavies"
    "profile_img": "jGFURuvM_400x400.png"
    "topic": "What Is A Static Site Generator"
    "patreon_link": ""
  -
    "guest": "Adam Argyle"
    "date": ""
    "twitter_handle": "argyleink"
    "profile_img": "FBpNyCPZ_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Chris Cornutt"
    "date": ""
    "twitter_handle": "enygma"
    "profile_img": "NbOZ5DIm_200x200.jpg"
    "topic": ""
    "patreon_link": ""



guests:
  -
    "name": ""
    "profile_image": ""
    "link": ""
    "bio": ""
    "episodes":
        -
          "title" : ""
          "link " : ""
          "publication_date": ""