google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: dQK1frHIpkQ
    podcast_id: 10000337
    guest: Drew McLellan
    guests_twitter: drewm
    profile_img: xBrKM3Vg_400x400.jpg

schedule:
  -
    "guest": "Josh Hudson"
    "date": "07-06-2019"
    "twitter_handle": "joshyhud"
    "profile_img": "YlM2119p_400x400.jpg"
    "topic": "From Call Center To Coder"
    "patreon_link": ""
 -
    "guest": "Jacques Woodcock"
    "date": ""
    "twitter_handle": "jacqueswoodcock"
    "profile_img": "PROx6DC0_400x400.jpeg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Emma Wedekind"
    "date": ""
    "twitter_handle": "EmmaWedekind"
    "profile_img": "mIOWZK8h_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Chris Cornutt"
    "date": ""
    "twitter_handle": "enygma"
    "profile_img": "NbOZ5DIm_200x200.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Stephen Doherty"
    "date": ""
    "twitter_handle": "thestemado"
    "profile_img": "cLquJrfv_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Stephanie Hurlburt"
    "date": ""
    "twitter_handle": "sehurlburt"
    "profile_img": "JvTb_YVy_400x400.jpg"
    "topic": ""
    "patreon_link": ""


guests:
  -
    "name": ""
    "profile_image": ""
    "link": ""
    "bio": ""
    "episodes":
        -
          "title" : ""
          "link " : ""
          "publication_date": ""