google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: V4tudla_euU
    podcast_id: 9544310
    guest: Kimberley Cook - codebar
    guests_twitter: codebar
    profile_img: NA5jYXmm_400x400.jpg

schedule:
  - 
    "guest": "Tom Vorel"
    "date": "2019-05-03"
    "twitter_handle": "tomasvorel13"
    "profile_img": "CMCNNCGx_400x400.jpg"
    "topic": "Best self taught developer resources"
    "patreon_link": "https://www.patreon.com/posts/best-self-taught-25725332"
  - 
    "guest": "John Jacob"
    "date": "2019-05-10"
    "twitter_handle": "johnsalzarulo"
    "profile_img": "7hw_saAP_400x400.jpg"
    "topic": "Iteration Podcast"
    "patreon_link": "https://www.patreon.com/posts/25768403"
  - 
    "guest": "Rob Waller"
    "date": "2019-05-17"
    "twitter_handle": "RobDWaller"
    "profile_img": "uCplUZ1P_400x400.jpg"
    "topic": "Testing To Break - TDD"
    "patreon_link": "https://www.patreon.com/posts/25768628"
  - 
    "guest": "Rob Wilson"
    "date": ""
    "twitter_handle": "devtoolboxuk"
    "profile_img": "eTL5nGaH_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  - 
    "guest": "Drew McLellan"
    "date": ""
    "twitter_handle": "drewm"
    "profile_img": "xBrKM3Vg_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  - 
    "guest": "Jacques Woodcock"
    "date": ""
    "twitter_handle": "jacqueswoodcock"
    "profile_img": "PROx6DC0_400x400.jpeg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Emma Wedekind"
    "date": ""
    "twitter_handle": "EmmaWedekind"
    "profile_img": "mIOWZK8h_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Chris Cornutt"
    "date": ""
    "twitter_handle": "enygma"
    "profile_img": "NbOZ5DIm_200x200.jpg"
    "topic": ""
    "patreon_link": ""