google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: ejDKauZZr7o
    podcast_id: 10239467
    guest: Stephen Doherty
    guests_twitter: thestemado
    profile_img: cLquJrfv_400x400.jpg

schedule:
  -
    "guest": "Emma Wedekind"
    "date": "28-06-19"
    "twitter_handle": "EmmaWedekind"
    "profile_img": "mIOWZK8h_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Jacques Woodcock"
    "date": ""
    "twitter_handle": "jacqueswoodcock"
    "profile_img": "PROx6DC0_400x400.jpeg"
    "topic": ""
    "patreon_link": ""

  -
    "guest": "Chris Cornutt"
    "date": ""
    "twitter_handle": "enygma"
    "profile_img": "NbOZ5DIm_200x200.jpg"
    "topic": ""
    "patreon_link": ""



guests:
  -
    "name": ""
    "profile_image": ""
    "link": ""
    "bio": ""
    "episodes":
        -
          "title" : ""
          "link " : ""
          "publication_date": ""