google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: j9oBzlfex6g
    podcast_id: 10325870
    guest: Emma Wedekind
    guests_twitter: EmmaWedekind
    profile_img: 91rCpayn_400x400.jpg

schedule:

  -
    "guest": "Jacques Woodcock"
    "date": "05-07-2019"
    "twitter_handle": "jacqueswoodcock"
    "profile_img": "PROx6DC0_400x400.jpeg"
    "topic": "What It's Like Working At Amazon As A Development Manager"
    "patreon_link": ""
  -
    "guest": "Adam Argyle"
    "date": ""
    "twitter_handle": "argyleink"
    "profile_img": "FBpNyCPZ_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Chris Cornutt"
    "date": ""
    "twitter_handle": "enygma"
    "profile_img": "NbOZ5DIm_200x200.jpg"
    "topic": ""
    "patreon_link": ""



guests:
  -
    "name": ""
    "profile_image": ""
    "link": ""
    "bio": ""
    "episodes":
        -
          "title" : ""
          "link " : ""
          "publication_date": ""