google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: yS8qR-XlrqE
    podcast_id: 11417078
    guest: Kyle Cook
    guests_twitter: devsimplified
    profile_img: XBSj69e5_400x400.jpg

schedule:
  -
    "guest": "Jenna Charlton"
    "date": ""
    "twitter_handle": "shewrestlestest"
    "profile_img": "7E_KIXO9_400x400.jpg"
    "topic": "Software Testing"
    "patreon_link": ""
  -
    "guest": "Jeremy Onion"
    "date": ""
    "twitter_handle": "balther74"
    "profile_img": "8avDLD-t_400x400.jpg"
    "topic": "Podcast Take Over"
    "patreon_link": ""
  -
    "guest": "Ted M. Young"
    "date": ""
    "twitter_handle": "jitterted"
    "profile_img": "XPKUbsRD_400x400.jpg"
    "topic": "Teaching Java and TDD"
    "patreon_link": ""
  -
    "guest": "Matthew Glen"
    "date": ""
    "twitter_handle": "mattyggg1"
    "profile_img": "3A_ttBlz_400x400.jpg"
    "topic": "Getting Into The Web Development Industry"
    "patreon_link": ""
  -
    "guest": "Adam Culp"
    "date": ""
    "twitter_handle": "adamculp"
    "profile_img": "n4Y3CzVa_400x400.png"
    "topic": "Beachcasts and YouTube"
    "patreon_link": ""
  -
    "guest": "Drew McLellan"
    "date": ""
    "twitter_handle": "drewm"
    "profile_img": "xBrKM3Vg_400x400.jpg"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Lynn Dang"
    "date": ""
    "twitter_handle": "LynnDangAU"
    "profile_img": "xqsAO_4I_400x400.jpg"
    "topic": "TBD"
    "patreon_link": ""