google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: NiWa2I2HsrM
    podcast_id: 11692328
    guest: Jenna Charlton
    guests_twitter: shewrestlestest
    profile_img: 7E_KIXO9_400x400.jpg

schedule:
  -
    "guest": "Jonan Scheffler"
    "date": "15-11-2019"
    "twitter_handle": "thejonanshow"
    "topic": "What To Expect From Junior Web Developers"
    "patreon_link": "https://www.patreon.com/posts/31415706"
  -
    "guest": "Susanna D. Kline"
    "date": ""
    "twitter_handle": "sdk_irl"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Drew McLellan"
    "date": ""
    "twitter_handle": "drewm"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Lynn Dang"
    "date": ""
    "twitter_handle": "LynnDangAU"
    "topic": "TBD"
    "patreon_link": ""