google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: 4PBtSJcyKts
    podcast_id: 12871709
    guest: Richard Bell
    guests_twitter: richard_bell

schedule:

  -
    "guest": "Matt Brunt"
    "date": ""
    "twitter_handle": "Brunty"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Susanna D. Kline"
    "date": ""
    "twitter_handle": "sdk_irl"
    "topic": "TBD"
    "patreon_link": ""

