google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: m4SsnGAwgSA
    podcast_id: 10418921
    guest: Jacques Woodcock
    guests_twitter: jacqueswoodcock
    profile_img: PROx6DC0_400x400.jpeg

schedule:
  -
    "guest": "Ines van Essen"
    "date": ""
    "twitter_handle": "motherofcode"
    "profile_img": "t-MDnclS_400x400.jpg"
    "topic": "Donate WC (WordPress Camp)"
    "patreon_link": ""
  -
    "guest": "Adam Argyle"
    "date": ""
    "twitter_handle": "argyleink"
    "profile_img": "FBpNyCPZ_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Chris Cornutt"
    "date": ""
    "twitter_handle": "enygma"
    "profile_img": "NbOZ5DIm_200x200.jpg"
    "topic": ""
    "patreon_link": ""



guests:
  -
    "name": ""
    "profile_image": ""
    "link": ""
    "bio": ""
    "episodes":
        -
          "title" : ""
          "link " : ""
          "publication_date": ""