google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: kn9_cJfASMY
    podcast_id: 11149400
    guest: Anna Filina
    guests_twitter: afilina
    profile_img: GWANUhbt_400x400.jpg

schedule:
  -
    "guest": "Jessica Smith"
    "date": "13-09-2019"
    "twitter_handle": "MintopiaUK"
    "profile_img": "oBE-lX7w_400x400.jpg"
    "topic": "Web Development Side Projects"
    "patreon_link": ""
  -
    "guest": "Gary Hockin"
    "date": ""
    "twitter_handle": "GeeH"
    "profile_img": "MLDDn1Uw_400x400.jpg"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Lynn Dang"
    "date": ""
    "twitter_handle": "LynnDangAU"
    "profile_img": "xqsAO_4I_400x400.jpg"
    "topic": "TBD"
    "patreon_link": ""