google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: ojOSJnMkOFg
    podcast_id: 10672058
    guest: Scott W. Ambler
    guests_twitter: scottwambler
    profile_img: 7WBAnFQz_400x400.jpeg

schedule:
  -
    "guest": "Anna Filina"
    "date": ""
    "twitter_handle": "afilina"
    "profile_img": "GWANUhbt_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Adam Argyle"
    "date": ""
    "twitter_handle": "argyleink"
    "profile_img": "FBpNyCPZ_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Chris Cornutt"
    "date": ""
    "twitter_handle": "enygma"
    "profile_img": "NbOZ5DIm_200x200.jpg"
    "topic": ""
    "patreon_link": ""



guests:
  -
    "name": ""
    "profile_image": ""
    "link": ""
    "bio": ""
    "episodes":
        -
          "title" : ""
          "link " : ""
          "publication_date": ""