google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: AlIe4LoRnKo
    podcast_id: 9105707
    guest: Olivia Liddell
    guests_twitter: oliravi
    profile_img: TSlMrGu0_400x400.jpg

schedule:
  - 
    "guest": "Jeremy Onion"
    "date": "2019-04-05"
    "twitter_handle": "balther74"
    "profile_img": "8avDLD-t_400x400.jpg"
    "topic": "Recuritment CV writing and interviews"
    "patreon_link": "https://www.patreon.com/posts/25715162"
  - 
    "guest": "Oliver Davies"
    "date": "2019-04-12"
    "twitter_handle": "opdavies"
    "profile_img": "MwrJuJM__400x400.png"
    "topic": "Drupal 7 vs Drupal 8"
    "patreon_link": "https://www.patreon.com/posts/25715232"
  - 
    "guest": "Matt Trask"
    "date": "2019-04-19"
    "twitter_handle": "matthewtrask"
    "profile_img": "CYhzS7dJ_400x400.png"
    "topic": "Mental health in web development"
    "patreon_link": ""
  - 
    "guest": "Code Bar"
    "date": "2019-04-26"
    "twitter_handle": "codebar"
    "profile_img": "NA5jYXmm_400x400.jpg"
    "topic": "Learning to code at Codebar"
    "patreon_link": "https://www.patreon.com/posts/25716536"
  - 
    "guest": "Tom Vorel"
    "date": "2019-05-03"
    "twitter_handle": "tomasvorel13"
    "profile_img": "CMCNNCGx_400x400.jpg"
    "topic": "Best self taught developer resources"
    "patreon_link": "https://www.patreon.com/posts/best-self-taught-25725332"
  - 
    "guest": "John Jacob"
    "date": "2019-05-10"
    "twitter_handle": "johnsalzarulo"
    "profile_img": "7hw_saAP_400x400.jpg"
    "topic": "Iteration Podcast"
    "patreon_link": ""
  - 
    "guest": "Rob Waller"
    "date": ""
    "twitter_handle": "RobDWaller"
    "profile_img": "uCplUZ1P_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  - 
    "guest": "Rob Wilson"
    "date": ""
    "twitter_handle": "devtoolboxuk"
    "profile_img": "eTL5nGaH_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  - 
    "guest": "Drew McLellan"
    "date": ""
    "twitter_handle": "drewm"
    "profile_img": "xBrKM3Vg_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  - 
    "guest": "Jacques Woodcock"
    "date": ""
    "twitter_handle": "jacqueswoodcock"
    "profile_img": "PROx6DC0_400x400.jpeg"
    "topic": ""
    "patreon_link": ""
    

