google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: nma7HTgh7_E
    podcast_id: 14035364
    guest: Emily Wallace Price
    guests_twitter: EmilyWallacePr2

schedule:
