google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: Rih21K8KBjI
    embed_src: https://anchor.fm/howtocodewell/embed/episodes/S3-EP-79-Deep-Dive-Into-Agile-With-Chris-Ginn---HTCW-Podcast-ejrg2r
    guest: Chris Ginn
    guests_twitter: chris_ginn.jpg

schedule:
