google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: gH77f_s_tas
    podcast_id: 11043158
    guest: Jessica Smith
    guests_twitter: MintopiaUK
    profile_img: oBE-lX7w_400x400.jpg

schedule:
  -
    "guest": "Gary Hockin"
    "date": ""
    "twitter_handle": "GeeH"
    "profile_img": "MLDDn1Uw_400x400.jpg"
    "topic": "Live Coding on Twitch and working at Twilio"
    "patreon_link": ""
  -
    "guest": "Lynn Dang"
    "date": ""
    "twitter_handle": "LynnDangAU"
    "profile_img": "xqsAO_4I_400x400.jpg"
    "topic": "TBD"
    "patreon_link": ""