google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: EoLcxT6YcAY
    embed_src: https://anchor.fm/howtocodewell/embed/episodes/S3-EP-76-How-to-make-a-JavaScript-API-Client---How-To-Code-Well-Podcast-ehh7hh
    guest: Peter Fisher
    guests_twitter: pfwd

schedule:
