google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: 2WQMHSCIcME
    podcast_id: 13934909
    guest: Matt Brunt
    guests_twitter: Brunty

schedule:
