google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: bcWVO88UAUE
    embed_src: https://anchor.fm/howtocodewell/embed/episodes/S3-EP78-From-Database-Administrator-To-Agile-Delivery-Lead---Chris-Ginn-Interview---HTCW-Podcast-ejff64
    guest: Chris Ginn
    guests_twitter: chris_ginn.jpg

schedule:
