google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: XcFwZo_7Sng
    podcast_id: 10587986
    guest: Oliver Davies
    guests_twitter: opdavies
    profile_img: jGFURuvM_400x400.png

schedule:
  -
    "guest": "Scott W. Ambler"
    "date": "19-07-26"
    "twitter_handle": "scottwambler"
    "profile_img": "7WBAnFQz_400x400.jpeg"
    "topic": "Agile Development"
    "patreon_link": ""
  -
    "guest": "Adam Argyle"
    "date": ""
    "twitter_handle": "argyleink"
    "profile_img": "FBpNyCPZ_400x400.jpg"
    "topic": ""
    "patreon_link": ""
  -
    "guest": "Chris Cornutt"
    "date": ""
    "twitter_handle": "enygma"
    "profile_img": "NbOZ5DIm_200x200.jpg"
    "topic": ""
    "patreon_link": ""



guests:
  -
    "name": ""
    "profile_image": ""
    "link": ""
    "bio": ""
    "episodes":
        -
          "title" : ""
          "link " : ""
          "publication_date": ""