sculpin_content_types:
    posts:
        enabled: false
    episodes:
        path: _episodes
        permalink: episode/:slug_title
        layout: default
        singular_name: episode
        taxonomies:
            - guests

