google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: h9setNdFbnhc
    podcast_id: 12220910
    guest: Matt Stauffer
    guests_twitter: stauffermatt

schedule:

  -
    "guest": "Lynn Dang"
    "date": ""
    "twitter_handle": "LynnDangAU"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Drew McLellan"
    "date": ""
    "twitter_handle": "drewm"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Beau Simensen"
    "date": ""
    "twitter_handle": "beausimensen"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Susanna D. Kline"
    "date": ""
    "twitter_handle": "sdk_irl"
    "topic": "TBD"
    "patreon_link": ""

