google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: v0VYr10HKAQ
    embed_src: https://anchor.fm/howtocodewell/embed/episodes/S3-EP-77-How-Im-upgrading-a-headless-CMS-and-API-to-Symfony-5-and-PHP-8-ej52e7
    guest: Peter Fisher
    guests_twitter: pfwd

schedule:
