google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: NiWa2I2HsrM
    podcast_id: 11692328
    guest: Jenna Charlton
    guests_twitter: shewrestlestest
    profile_img: 7E_KIXO9_400x400.jpg

schedule:
  -
    "guest": "Adam Culp"
    "date": "01-11-2019"
    "twitter_handle": "adamculp"
    "topic": "Beachcasts and YouTube"
    "patreon_link": "https://www.patreon.com/posts/s2-ep44-adam-and-31042766"
  -
    "guest": "Ted M. Young"
    "date": "08-11-2019"
    "twitter_handle": "jitterted"
    "topic": "Teaching Java and TDD"
    "patreon_link": "https://www.patreon.com/posts/s2-ep45-teaching-31055516"
  -
    "guest": "Jonan Scheffler"
    "date": ""
    "twitter_handle": "thejonanshow"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Susanna D. Kline"
    "date": ""
    "twitter_handle": "sdk_irl"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Drew McLellan"
    "date": ""
    "twitter_handle": "drewm"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Lynn Dang"
    "date": ""
    "twitter_handle": "LynnDangAU"
    "topic": "TBD"
    "patreon_link": ""