google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: eevxWUgoxjU
    podcast_id: 10837238
    guest: Matt Brunt
    guests_twitter: Brunty
    profile_img: TjB9WT83_400x400.jpg

schedule:
  -
    "guest": "Jeremy Onion"
    "date": "16-08-2019"
    "twitter_handle": "balther74"
    "profile_img": "8avDLD-t_400x400.jpg"
    "topic": "Personal development and certifications"
    "patreon_link": ""
  -
    "guest": "Dave Darnes"
    "date": ""
    "twitter_handle": "DavidDarnes"
    "profile_img": "sk9aTJWb_400x400.jpg"
    "topic": "Publishing content with Ghost"
    "patreon_link": ""
  -
    "guest": "Anna Filina"
    "date": ""
    "twitter_handle": "afilina"
    "profile_img": "GWANUhbt_400x400.jpg"
    "topic": "Working on legacy code"
    "patreon_link": ""
  -
    "guest": "Gary Hockin"
    "date": ""
    "twitter_handle": "GeeH"
    "profile_img": "MLDDn1Uw_400x400.jpg"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Jessica Smith"
    "date": ""
    "twitter_handle": "MintopiaUK"
    "profile_img": "oBE-lX7w_400x400.jpg"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Lynn Dang"
    "date": ""
    "twitter_handle": "MintopiaUK"
    "profile_img": "xqsAO_4I_400x400.jpg"
    "topic": "TBD"
    "patreon_link": ""