google_tag_manager_id: foobar
active_google_tag_manager: false
url: https://howtocodewell.fm
meta:
    title: How To Code Well Podcast
    description: Weekly web development podcast with discussions from developers and industry leaders from within the industry

featured:
    youtubeId: NiWa2I2HsrM
    podcast_id: 11692328
    guest: Jenna Charlton
    guests_twitter: shewrestlestest
    profile_img: 7E_KIXO9_400x400.jpg

schedule:
  -
    "guest": "Adam Culp"
    "date": "01-09-2019"
    "twitter_handle": "adamculp"
    "profile_img": "n4Y3CzVa_400x400.png"
    "topic": "Beachcasts and YouTube"
    "patreon_link": ""
  -
    "guest": "Ted M. Young"
    "date": ""
    "twitter_handle": "jitterted"
    "profile_img": "XPKUbsRD_400x400.jpg"
    "topic": "Teaching Java and TDD"
    "patreon_link": ""
  -
    "guest": "Drew McLellan"
    "date": ""
    "twitter_handle": "drewm"
    "profile_img": "xBrKM3Vg_400x400.jpg"
    "topic": "TBD"
    "patreon_link": ""
  -
    "guest": "Lynn Dang"
    "date": ""
    "twitter_handle": "LynnDangAU"
    "profile_img": "xqsAO_4I_400x400.jpg"
    "topic": "TBD"
    "patreon_link": ""